[package]
name = "icns"
version = "0.2.1"
authors = ["Matthew D. Steele <mdsteele@alum.mit.edu>"]
description = "A library for encoding/decoding Apple Icon Image (.icns) files."
repository = "https://github.com/mdsteele/rust-icns"
documentation = "http://mdsteele.github.io/rust-icns/"
keywords = ["icns", "icon", "image"]
license = "MIT"

[dependencies]
byteorder = "1"
png = "0.6"
